# Generated by Django 3.1.7 on 2021-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210405_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='D:\\SS\\ecommerce_app\\ecommerce\\media\\shop\\images'),
        ),
    ]
